language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


before_script:
  - npm install -g gulp
  - npm install gulp gulp-minify-css gulp-htmlmin gulp-htmlclean --save
  - hexo clean


script:
  - hexo g
  - gulp

after_script:
  - cd ./public
  - git init
  - git config user.name "frank-xjh"
  - git config user.email "frank99-xu@outlook.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/frank-xjh/frank-xjh.github.io.git